/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reino_jogo;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Tarcyo
 */
public class Tela extends javax.swing.JFrame {

    private static int anos = 0;
    private static boolean eCasado = false;
    private static boolean medico = false;
    private static boolean bruxa = false;
    private static boolean trovador = false;
    private static boolean chefeguerreiro = false;
    private static boolean duque = false;
    private static boolean capitão = false;
    private static int igreja = 50;
    private static int exercito = 50;
    private static int povo = 50;
    private static int economia = 50;
    private static int consequencia;
    private static int rand;
    private static Random r = new Random();

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();

        pigreja.setText(igreja + "");
        ppovo.setText(povo + "");
        pexercito.setText(exercito + "");
        peconomia.setText(economia + "");
        ano.setText(anos + "");
        consequencia = acontecimento();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jDialog1 = new javax.swing.JDialog();
        direita = new javax.swing.JButton();
        esquerda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pigreja = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ppovo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pexercito = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        peconomia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        info = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ano = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        direita.setText("Opção Direita");
        direita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direitaActionPerformed(evt);
            }
        });

        esquerda.setText("Opção Esquerda");
        esquerda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esquerdaActionPerformed(evt);
            }
        });

        jLabel1.setText("Igreja");

        pigreja.setEditable(false);

        jLabel2.setText("Povo");

        ppovo.setEditable(false);

        jLabel3.setText("Exercito");

        pexercito.setEditable(false);

        jLabel4.setText("Economia");

        peconomia.setEditable(false);

        jLabel5.setText("Ano:");

        info.setEditable(false);

        jLabel7.setText("Informação do ano");

        ano.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ano))
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(esquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(direita, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pigreja, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ppovo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(pexercito, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(peconomia, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pigreja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ppovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(pexercito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(peconomia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(esquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direita, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void esquerdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esquerdaActionPerformed
        switch (consequencia) {
            case 1:
                economia = economia - 30;
                break;
            case 2:
                igreja = igreja - 10;
                povo = povo + 10;
                exercito = exercito + 10;
                bruxa = true;
                break;
            case 3:
                povo = povo + 10;
                exercito = exercito + 10;
                igreja = igreja + 10;
                economia = economia + 10;
                eCasado = true;
                break;
            case 4:
                povo = povo - 20;
                economia = economia + 20;
                break;
            case 5:
                economia = economia - 25;
                povo = povo + 10;
                economia = economia + 10;
                igreja = igreja + 10;
                break;
            case 6:
                economia = economia - 15;
                povo = povo + 15;
                break;
            case 7:
                igreja = igreja + 20;
                economia = economia + 10;
                povo = povo - 15;
                exercito = exercito - 15;
                bruxa=false;
                break;
            case 8:
                povo = povo - 20;
                economia = economia + 20;
                break;
            case 9:
                igreja = igreja + 25;
                exercito = exercito - 10;
                break;
            case 10:
                exercito = exercito + 15;
                povo = povo - 20;
                break;
            case 11:
                economia = economia - 15;
                povo = povo + 15;
                break;
            case 12:
                economia = economia - 25;
                povo = povo + 20;
                break;
            case 13:
                povo = povo - 25;
                economia = economia + 30;
                break;
            case 14:
                povo = povo + 5;
                economia = economia - 10;
                break;
            case 15:
                povo = povo + 20;
                economia = economia + 5;
                exercito = exercito + 5;
                igreja = igreja + 5;
                break;
            case 16:
                economia = economia + 5;
                povo = povo - 5;
                exercito = exercito - 5;
                igreja = igreja - 5;

                break;
            case 17:
                povo = povo - 15;
                exercito = exercito - 15;
                economia = economia - 15;
                igreja = igreja - 15;
                break;
            case 18:
                anos = Integer.parseInt(ano.getText()) + 10;
                ano.setText(anos + "");
                break;
            case 19:
                economia = economia + 20;
                break;
            case 20:
                povo = povo - 15;
                break;
            case 21:
                povo = povo + 15;
                igreja = igreja - 15;
                break;
            case 22:
                igreja += 10;
                exercito += 10;
                economia += 10;

                povo = povo - 5;
                break;
            case 23:
                economia -= 25;
                povo = povo + 10;
                break;
            case 24:
                povo = povo + 20;
                igreja = igreja - 10;
                break;
            case 25:
                System.out.println("KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK");
                break;
            case 26:
                economia = economia + 20;
                igreja = igreja - 10;
                break;
            case 27:
                exercito = exercito + 10;
                igreja = igreja - 10 ;
                break;
            case 28:
                exercito = exercito - 25  ;
                povo = povo + 10;
                break;
            case 29:
                povo = povo + 15;
                exercito = exercito - 5;
                economia = economia - 5;
                igreja = igreja + 15;
                duque = true;  
                break;
            case 30:
                povo = povo + 5;
                igreja = igreja - 5;
                economia = economia - 5;
                break;
            case 31:
                exercito += 15;
                economia += 10;
                povo -= 10;
                igreja -= 15;
                chefeguerreiro = true;
                break;
            case 32:
                igreja = igreja - 20;
                exercito = exercito + 20;
                povo = povo - 5;
                economia = economia + 5;
                break;
            case 33:
                povo += 20;
                economia += 20;
                exercito -= 15;
                igreja -= 15;
                break;
            case 34:
                economia = economia + 15;
                povo = povo - 1;
                break;
            case 35:
                igreja += 20;
                economia = economia + 5;
                povo = povo - 20;
                exercito = exercito - 10;
                break;
            case 36:
                igreja = 50;
                economia = 50;
                povo = 50;
                exercito = 50;
                break;
            case 37:
                igreja = 80;
                economia = 80;
                povo = 80;
                exercito = 80;
                break;
            case 38:
                povo = povo - 5;
                economia = economia - 20;
                break;
            case 39:
                economia = economia - 10;
                povo = povo + 15 ;
                igreja = igreja - 15;
                break;
            case 40:
                igreja += 15;
                exercito += 15;
                povo = povo - 20;
                economia = economia - 20;
                break;
            case 41:
                economia = economia - 15;
                povo += 10;
                exercito = exercito += 10;
                igreja += 10;
                break;
            case 42:
                povo = povo + 20;
                exercito = exercito + 20;
                economia = economia - 10;
                igreja = igreja - 10;
                break;
            case 43:
                economia = economia + 20;
                povo = povo - 5;
                igreja = igreja - 5;
                exercito = exercito - 5;
                capitão=true;
                break;
            case 44:
                economia = economia + 15;
                povo = povo - 5;
                igreja = igreja - 5;
                exercito = exercito - 5;
                break;
            case 45:
                economia = economia - 30;
                exercito = exercito - 10;
                break;
            case 46:
                exercito=exercito-15;
                povo+=15;
                igreja+=15;
                economia=economia-15;
                break;
            case 47:
                igreja-=15;
                povo-=15;
                economia-=15;
                exercito-=15;
                break;
                
                
        }
        verifica();


    }//GEN-LAST:event_esquerdaActionPerformed

    private void direitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direitaActionPerformed
        switch (consequencia) {
            case 1:
                povo=povo-30 ;
                break;
            case 2:
                igreja = igreja + 10;
                povo = povo - 10;
                exercito = exercito - 10;
                break;
            case 3:
                povo = povo - 1;
                exercito = exercito - 1;
                igreja = igreja - 1;
                economia = economia - 1;
                break;
            case 4:
                povo = povo +20;
                economia = economia - 20;
                break;
            case 5:
                economia = economia +10;
                povo = povo - 10;
                economia = economia - 10;
                igreja = igreja -10;
                break;
            case 6:
                povo = povo - 20;
                break;
            case 7:
                igreja = igreja - 20;
                povo = povo + 15;
                exercito = exercito + 15;
                break;
            case 8:
                povo = povo +20;
                economia = economia - 20;
                break;
            case 9:
                igreja = igreja - 10;
                exercito = exercito + 20;
                break;
            case 10:
                exercito = exercito - 20;
                
                break;
            case 11:
                
                povo = povo - 20;
                break;
            case 12:
               
                povo = povo - 15;
                break;
            case 13:
                povo = povo + 20;
               
                break;
            case 14:
                povo = povo - 15;
                economia = economia+ 10;
                break;
            case 15:
                povo = povo + 5;
                economia = economia + 5;
                exercito = exercito + 15;
                igreja = igreja + 5;
                break;
            case 16:
                economia = economia -15;
               

                break;
            case 17:
                
                exercito = exercito - 30;
                
                break;
            case 18:
               povo--;
               igreja--;
               exercito--;
               economia--;
                break;
            case 19:
               povo=povo+5;
               igreja=igreja+5;
               exercito=exercito+5;
                break;
            case 20:
                economia = economia - 15;
                break;
            case 21:
                povo = povo - 15;
                igreja = igreja + 15;
                break;
            case 22:
                
                povo = povo +25;
                break;
            case 23:
                economia +=10;
                povo = povo - 20;
                break;
            case 24:
                
                igreja = igreja + 5;
                break;
            case 25:
                System.out.println("KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK");
                break;
            case 26:
                economia = economia - 20;
                igreja = igreja + 15;
                break;
            case 27:
                exercito = exercito - 15;

                igreja = igreja +15;
                break;
            case 28:
                exercito+=5;
                povo = povo - 20;
                break;
            case 29:
              exercito=exercito+15;
                break;
            case 30:
                igreja+=5;
               
                break;
            case 31:
                exercito-=15;
                igreja+=15;
                
                break;
            case 32:
                igreja = igreja + 20;
                exercito = exercito - 20;
               
                break;
            case 33:
                exercito=exercito+15;
                break;
            case 34:
                economia = economia - 1;
                povo = povo + 15;
                break;
            case 35:
                igreja -=20;
                economia = economia -5;
                povo = povo + 20;
                exercito = exercito + 10;
                break;
            case 36:
                System.err.println("juhdsf");
                break;
            case 37:
               System.err.println("juhdsf");
                break;
            case 38:
                povo = povo - 20;
                
                break;
            case 39:
                economia = economia + 10;
                povo = povo - 20;
                igreja = igreja + 15;
                break;
            case 40:
                igreja -= 25;
                exercito -= 25;
                povo = povo + 20;
                economia = economia + 20;
                break;
            case 41:
                economia = economia + 10;
                povo -= 20;
                exercito = exercito -= 20;
                igreja -= 20;
                break;
            case 42:
                povo = povo - 20;
                exercito = exercito - 20;
               
                igreja = igreja + 10;
                break;
            case 43:
                
                povo = povo + 10;
                igreja = igreja + 10;
                exercito = exercito + 10;
                break;
            case 44:
               
                povo = povo + 10;
                igreja = igreja + 10;
                exercito = exercito + 10;
                break;
            case 45:
                economia = economia - 20;
                igreja = igreja - 10;
                break;
            case 46:
                exercito=exercito+10;
                povo-=10;
                igreja-=10;
                economia=economia+10;
                break;
            case 47:
                
               
                exercito-=20;
                break;
                
        }
        verifica();
    }//GEN-LAST:event_direitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);

            }
        });
    }

    private int acontecimento() {
        int a = r.nextInt(49) + 1;
        if (a == 1) {
            info.setText("O castelo está pegando fogo!");
            esquerda.setText("Salvar as pessoas");
            direita.setText("Salvar o Dinheiro");
            return 1;

        }
        if (a == 2) {
            if (bruxa == false) {
                info.setText("Uma bruxa curandeira quer entrar na corte");
                esquerda.setText("Deixar");
                direita.setText("Negar");
                return 2;
            }

        }
        if (a == 3) {
            if (eCasado == false) {
                info.setText("O reino vizinho está propondo casamento com uma jovem princesa.");
                esquerda.setText("Casar");
                direita.setText("Não");
                return 3;
            }

        }
        if (a == 4) {
            info.setText("Ouve uma explosão na mina");
            esquerda.setText("Continuar cavando");
            direita.setText("Salvar as vítimas");
            return 4;
        }
        if (a == 5) {
            info.setText("Um terremoto destruiu a capital");
            esquerda.setText("Salve as vítimas");
            direita.setText("Evite saques");
            return 5;
        }
        if (a == 6) {
            info.setText("Um assasino está matando pessoas e só irá parar caso o paguem.");
            esquerda.setText("Pagar");
            direita.setText("Ignorar");
            return 6;
        }
        if (a == 7) {
            info.setText("A igreja exige  uma caça as bruxas");
            esquerda.setText("Deixar");

            direita.setText("Impedir");
            return 7;
        }
        if (a == 8) {
            info.setText("Ouve uma explosão na mina");
            esquerda.setText("Continuar cavando");
            direita.setText("Salvar as vítimas");
            return 8;
        }
        if (a == 9) {
            if (eCasado == true) {
                info.setText("Sua esposa está gravida! quem será o pradrinho?");
                esquerda.setText("O Padre");
                direita.setText("O General");

                return 9;
            }

            return acontecimento();
        }
        if (a == 10) {
            info.setText("O exercito foi derrotado precisamos recrutar a população");
            esquerda.setText("Sim");
            direita.setText("Não");
            return 10;
        }
        if (a == 11) {
            info.setText("O rio secou precisamos contruir uma barragem");
            esquerda.setText("Sim");
            direita.setText("Não");
            return 11;
        }
        if (a == 12) {
            info.setText("Precisamos limpar o pantâno");
            esquerda.setText("Sim");
            direita.setText("Naõ");
            return 12;
        }
        if (a == 13) {
            info.setText("Podemos investir em trabalho escravo");
            esquerda.setText("Sim");
            direita.setText("Não");
            return 13;
        }
        if (a == 14) {
            info.setText("A Colheita foi péssima");
            esquerda.setText("Diminuir impostos");
            direita.setText("Aumentar impostos");
            return 14;
        }
        if (a == 15) {
            info.setText("A colheita foi fantastica");
            esquerda.setText("Alimente o povo ");
            direita.setText("Alimente o exercito");
            return 15;
        }
        if (a == 16) {
            info.setText("A inflação está aumentando, precisamos de uma reforma monetária");
            esquerda.setText("Sim ");
            direita.setText("Não");
            return 16;
        }
        if (a == 17) {
            info.setText("Perdemos a guerra, presisamos fazer um acordo");
            esquerda.setText("Sim ");
            direita.setText("Não");
            return 17;
        }
        if (a == 18) {
            info.setText("Podemos assinar um acordo comercial que nos propoecionará 10 anos de paz.");
            esquerda.setText("Sim ");
            direita.setText("Não");
            return 18;
        }
        if (a == 19) {
            info.setText("Achamos ouro nas minas");
            esquerda.setText("È meu");
            direita.setText("È nosso");
            return 19;
        }
        if (a == 20) {
            info.setText("A cidade está em crise");
            esquerda.setText("Culpe o prefeito ");
            direita.setText("Culpe os comerciantes");
            return 20;
        }
        if (a == 21) {

            if (eCasado == true) {
                info.setText("Sua esposa está morrendo");
                esquerda.setText("chamar o médico ");
                direita.setText("Orar");
                eCasado = false;
                return 21;

            }

        }
        if (a == 22) {
            info.setText("A caça foi muito boa.");
            esquerda.setText(" Fazer um banquete");
            direita.setText("Alimentar as pessoas");
            return 22;
        }

        if (a == 23) {
            info.setText("A colheita foi fraca");
            esquerda.setText("Dar suprimentos");
            direita.setText("Aumentar impostos");
            return (23);
        }
        if (a == 24) {
            if (eCasado == true) {
                info.setText("Uma mulher está te mandando cartas pedindo ser sua amante");
                esquerda.setText("Aceitar");
                direita.setText("Negar");
                return 24;
            }
        }
        if (a == 25) {
            info.setText("Literalmente nada acontecendo...");
            esquerda.setText("...");
            direita.setText("...");
            return 25;
        }
        if (a == 26) {
            info.setText("Os comerciantes estão cobrando imposto da abadia");
            esquerda.setText("Deixar");
            direita.setText("Impidir");
            return 26;
        }
        if (a == 27) {
            info.setText("Os soldados estão cobrando dos padres em troca de proteção");
            esquerda.setText("Deixar");
            direita.setText("Impidir");
            return 27;
        }
        if (a == 28) {
            info.setText("O povo esta exigindo uma reforma contituinte que reduza o poder do exercito");
            esquerda.setText("Sim");
            direita.setText("Não");
            return 28;
        }

        if (a == 29) {
            if (duque == false) {
                info.setText("Um duque do reino do leste quer uma posição na corte");
                esquerda.setText("Sim");
                direita.setText("Não");
                // duque = true;
                return 29;
            }
        }
        if (a == 30) {
            if (bruxa == true) {
                info.setText("A bruxa quer ler sua sorte");
                esquerda.setText("Sim");
                direita.setText("Não");
                return 30;
            }
        }
        if (a == 31) {
            if (chefeguerreiro == false) {
                info.setText("O chefe de guerra do oeste quer um lugar na corte");
                esquerda.setText("Sim");
                direita.setText("Não");
                return 31;
            }
        }
        if (a == 32) {
            if (chefeguerreiro == true) {
                info.setText("O chefe de guerra quer fudir seu exercito mas a igreja não gosta dele");
                esquerda.setText("Sim");
                direita.setText("Não");
                return 32;
            }
        }
        if (a == 33) {
            if (duque == true) {
                info.setText("O duque quer aprovação para aceitar refugiados do leste");
                esquerda.setText("Sim");
                direita.setText("Não");
                return 33;
            }
        }
        if (a == 34) {
            info.setText("Quem será convidado para ser o palestrante no banquete de inverno?");
            esquerda.setText("O Mestre da guilda dos comerciantes");
            direita.setText("O prefeito");
            return 34;
        }
        if (a == 35) {
            info.setText("A igreja quer que as festas sejam mais castas");
            esquerda.setText("Sim");
            direita.setText("Não");
            return 35;
        }
        if (a == 36) {
            info.setText("Podemos realizar uma reforma política que nos trará estabilidade mas teremos que nos desfazer do que fizemos até agora. ");
            esquerda.setText("Realizar");
            direita.setText("Manter");
            return 36;
        }
        if (a == 37) {
            info.setText("Podemos estbelecer colonias no norte, mas precisamos estar preparados para gerir");
            esquerda.setText("Sim");
            direita.setText("Não");
            return 37;
        }
        if (a == 38) {
            info.setText("A peste negra está matando a população");
            esquerda.setText("Tratar a população");
            direita.setText("Fechar os portãoes do castelo");
            return 38;
        }
        if (a == 39) {
            info.setText("Como o seu castelo deve ser decorado");
            esquerda.setText("Ouro");
            direita.setText("Simples");
            return 39;
        }
        if (a == 40) {
            info.setText("Os campos estão alagando, quem será salvo?");
            esquerda.setText("A igreja e o exercito");
            direita.setText("O povo e a colheita");
            return 40;
        }
        if (a == 41) {
            info.setText("Uma praga está matando toda população.");
            esquerda.setText("Colocar todos em quarentena");
            direita.setText("Fingir que nada está acontecendo");
            return 41;
        }
        if (a == 42) {
            if (bruxa == true) {
                info.setText("A bruxa quer abrir um hospital para prevenir epidemias");
                esquerda.setText("Sim");
                direita.setText("Não");
                return 42;
            }
        }
        if (a == 43) {
            if (capitão == false) {
                info.setText("Um capitão pirata quer um lugar na corte");
                esquerda.setText("Sim");
                direita.setText("Não");
             //   capitão = true;
                return 43;
            }

        }
        if (a == 44) {
            if (capitão == true) {
                info.setText("O capitão está oferecendo tesouros em troca de ajuda em um golpe narítimo no oriente.");
                esquerda.setText("Sim");
                direita.setText("Não");
                return 44;
            }
        }
        if (a == 45) {
            if (capitão == true) {
                info.setText("òh não !!!! o capitão roubou o tesouro do castelo e fugiu!!!!");
                esquerda.setText("ENFIE O EXERCITO A PROCURA");
                direita.setText("PEDIR AJUDA Á IGREJA");
                capitão = false;
                return 45;
            }
            
        }
        if(a==46){
            if(duque==true){
                info.setText("O duque pretende deixar a corte.");
                esquerda.setText("Deixar ficar");
                direita.setText("Já vai tarde  ");
                return 46;
            }
        }
        if(a==47){
            if(chefeguerreiro==true){
                info.setText("O chefe de guerra se revoltou e declarou guerra ao reino.");
                esquerda.setText("Atacar");
                direita.setText("Defender  ");
                chefeguerreiro = false;
                return 47;
            }
            
        }
        return acontecimento();
    }

    private void verifica() {
        ppovo.setText(povo + "");
        peconomia.setText(economia + "");
        pexercito.setText(exercito + "");
        pigreja.setText(igreja + "");
        anos += 1;
        ano.setText(anos + "");
       if (igreja > 99 || igreja < 1 || povo > 99 || povo < 1 || economia > 99 || economia < 1 || exercito > 99 || exercito < 1) {
            JOptionPane.showMessageDialog(rootPane, "Infelizmente o poder entrou em desequilibriu e seu povo se revoltou");
            JOptionPane.showMessageDialog(rootPane, "VocÊ foi guilhotinado.");
            JOptionPane.showMessageDialog(rootPane, "Seu recorde foi " + anos + "anos");
            this.dispose();

        }
        if (anos > 99) {
            JOptionPane.showMessageDialog(rootPane, "Você está morrendo de velhice");
            JOptionPane.showMessageDialog(rootPane, "Você venceu!! PARABENS!!!");
            this.dispose();

        }
            
      //  System.out.println("\nano:"+anos+"\nIgreja: "+igreja+" \nPovo:"+povo+" \nExercito: "+exercito+"\nEconomia: "+ economia+"\n è casado?: "+eCasado+"\nBruxa: "+bruxa+"\nChefe guerreiro: "+chefeguerreiro+"\nDuque: "+duque+"Capitão: "+capitão);
        consequencia = acontecimento();

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ano;
    private javax.swing.JButton direita;
    private javax.swing.JButton esquerda;
    private javax.swing.JTextField info;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField peconomia;
    private javax.swing.JTextField pexercito;
    private javax.swing.JTextField pigreja;
    private javax.swing.JTextField ppovo;
    // End of variables declaration//GEN-END:variables
}
